version: '0.1'
services:
      database:
        image: postgres
        container_name: postgres_container
        ports:
          - "5432:5432"
        environment:
          - DATABASE_URL=${DATABASE_URL}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      next_app:
        image: next_blog
        container_name: next_container
        ports:
          - "3000:3000"
        environment:
          - AUTH_SECRET=${AUTH_SECRET}
          - AWS_REGION=${AWS_REGION}
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
          - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
          - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
          - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
          - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
          - DATABASE_URL=${DATABASE_URL}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

